baseURL = "https://benji-bloom-portfolio.netlify.app/"
locale = "en-us"
title = "Benji Bloom"
disableKinds = ["taxonomy", "term"]

[params]
  description = "Describe your website"

  # Nav links in the header
  [[params.navlinks]]
  name = "Work"
  url = "/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

[services]
  [services.googleAnalytics]
    ID = 'G-L15E732RKV'

[markup]
  [markup.goldmark.renderer]
    hardWraps = true
