baseURL = "https://benji-bloom-portfolio.netlify.app/"
languageCode = "en-us"
title = "Benji Bloom"
theme = "hugo-creative-portfolio-theme"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "Describe your website"
  copyright = "&copy;2025 Benji Bloom"
  sidebarAbout = [""]
  # Contact page
  email = "you@yoursite.com"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

[services]
  [services.googleAnalytics]
    ID = 'G-L15E732RKV'

[markup]
  [markup.goldmark.renderer]
        hardWraps = true
