[build]
publish = "public"
command = "npm run tailwind:build && hugo"

[build.environment]
  HUGO_VERSION = "0.111.3"
  NODE_VERSION = "18.16.0"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "npm run tailwind:build && hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "npm run tailwind:build && hugo -b $DEPLOY_PRIME_URL"